\getenv DB KESTRA_POSTGRES_DB
\getenv USER KESTRA_POSTGRES_USER
\getenv PASSWORD KESTRA_POSTGRES_PASSWORD

CREATE USER :DB WITH PASSWORD :'PASSWORD';
CREATE DATABASE :DB;
GRANT ALL PRIVILEGES ON DATABASE :DB TO :USER;

\c :DB postgres
\getenv USER KESTRA_POSTGRES_USER
GRANT ALL ON SCHEMA public TO :USER;
