id: get-data
namespace: olexya.data.games
inputs:
  - type: INT
    id: number_app
    defaults: 190
    description: Nombre d'app à télécharger
    required: false
    min: -1
tasks:
  - id: get-data
    type: io.kestra.plugin.scripts.python.Commands
    allowFailure: true
    beforeCommands:
      - pip install -r requirements.txt
    commands:
      - python main.py --app {{ inputs.number_app }}
    disabled: false
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: data-games-viz
  - id: build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    beforeCommands:
      - |
        while read line; do
          export $line
        done < .env
    commands:
      - 'mkdir /root/.dbt #'
      - 'cp ./profiles.yml /root/.dbt/ #'
      - 'dbt deps #'
      - 'dbt build #'
    containerImage: ghcr.io/kestra-io/dbt-postgres:latest
    disabled: false
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: data-games-viz
triggers:
  - id: start
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
    disabled: false
