# .github/workflows/update-tools-inventory.yml
name: Update Tools Inventory
on:
  schedule:
    - cron: '0 0 * * 1'  # Tous les lundis à minuit
  workflow_dispatch:      # Permet aussi le déclenchement manuel

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil pytz pandas
          
      - name: Update inventory files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/update_tools_inventory.py