name: Update Tools Inventory
on:
  schedule:
    - cron: '0 22 * * 0'  # Dimanche à 22h00
    - cron: '0 22 * * 3'  # Mercredi à 22h00
  workflow_dispatch:      # Permet aussi le déclenchement manuel

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Utilisez GITHUB_TOKEN au lieu de PAT_TOKEN
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil pytz pandas
          
      - name: Update inventory files
        env:
          # Utilisez GITHUB_TOKEN pour l'API GitHub
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: python .github/scripts/update_tools_inventory.py

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "Update tools inventory [automated]"
            git push
          else
            echo "No changes to commit"
          fi